class JsonData {
  static String englishJsonCode = "en";
  static Map englishJson = {
    englishJsonCode: {
      "ABOUT_US": "About Us",
      "ACCEPT_MSG": "Please Accept Privacy Policies and T&C",
      "ADD": "Add",
      "ADDRESS": "Address",
      "ADDRESS_MSG": "You have not selected any address yet!",
      "ADDRESS_TYPE": "Address Type",
      "ADD_NEW_ADDRESS": "Add New Address",
      "ADD_TO_CART": "Add to Cart",
      "ALL": "All",
      "ALL_CATEGROIES": "All Categories",
      "AMOUNT": "Amount",
      "AND": "and",
      "APARTMENT_NAME": "Apartment Name",
      "APPLY": "Apply",
      "APPLY_WALLET": "Apply Wallet",
      "BACK_TO_HOME": "Back to Home",
      "BALANCE": "Balance",
      "CALL_US": "Call Us",
      "CANCEL": "Cancel",
      "CANCELLED": "Cancelled",
      "CANCEL_ORDER": "Cancel Orders",
      "CART_SUMMARY": "Cart Summary",
      "CASH_ON_DELIVERY": "Cash On Delivery",
      "CHANGE": "Change",
      "CHANGE_MOBILE_NUMBER": "Change Mobile Number",
      "CHANGE_PASSWORD": "Change Password",
      "CHAT": "Chat",
      "CHAT_DETAIL": "Chat Detail",
      "CHECKOUT": "Checkout",
      "CHOOSE_DATE_TIME": "Choose Delivery Date and Time Slot",
      "CHOOSE_FROM_PHOTOS": "Choose From Photos",
      "CHOOSE_PAYMENT_METHOD": "Choose Payment Method",
      "CLEAR_CART": "Clear Cart",
      "CODE_MSG": "We have sent a 4 digits code to",
      "CONFIRMED": "Confirmed",
      "CONTACT_INFO": "Contact Information",
      "CONTACT_NUMBER": "Contact Number",
      "COUNTRY": "Country",
      "COUPON_APPLIED": "Coupon Applied",
      "COUPON_DISCOUNT": "Coupon Discount",
      "CREDIT": "Credit",
      "DATE": "Date",
      "DEAL": "Deal",
      "DEALS_OF_THE_DAYS": "Deals of The Days",
      "DEAL_AMOUNT": "Deal Amount",
      "DEBIT": "debit",
      "DELETE": "Delete",
      "DELIVERED": "Delivered",
      "DELIVERY_ADDESS": "Delivery Address",
      "DELIVERY_CHARGES": "Delivery Charges",
      "DELIVERY_DATE": "Delivery Date",
      "DELIVERY_TIME": "Delivery Time",
      "DESCRIPTION": "Description",
      "DISCOUNT": "Discount",
      "DO_NOT_ENTER_SAME_PASS":
          "Do not enter same old password and new password",
      "EDIT": "Edit",
      "EDIT_ADDRESS": "Edit Address",
      "EDIT_PROFILE": "Edit Profile",
      "EMAIL": "Email",
      "EMAIL_OPTIONAL": "Email (Optional)",
      "EMAIL_OR_MOBILE_NUMBER": "Email/Mobile Number",
      "ENTER_APARTMENT_NAME": "Enter Apartment Name",
      "ENTER_CONFIRM_PASSWORD": "Enter Confirm Password",
      "ENTER_CONTACT_NUMBER": "Enter Contact Number",
      "ENTER_COUPON_CODE": "Enter Coupon Code",
      "ENTER_FIRST_NAME": "Enter First Name",
      "ENTER_FULL_NAME": "Enter Full Name",
      "ENTER_HOUSE_FLAT_BLOCK_NUMBER": "Enter House/Flat/Block Number",
      "ENTER_LANDMARK": "Enter Landmark",
      "ENTER_LAST_NAME": "Enter Last Name",
      "ENTER_LOCATION": "Enter Location",
      "ENTER_NEW_PASSWORD": "Enter New Password",
      "ENTER_OLD_PASSWORD": "Enter Old Password",
      "ENTER_PASSWORD": "Enter Password",
      "ENTER_POSTAL_CODE": "Enter Postal Code",
      "ENTER_TEXT_HERE": "Enter Text Here",
      "ENTER_VERIFICATION_CODE": "Enter Verification Code",
      "ENTER_YOUR_CONTACT_NUMBER": "Enter Your Contact Number",
      "ENTER_YOUR_EMAIL": "Enter Your Email",
      "ENTER_YOUR_EMAIL_OR_MOBILE_NUMBER": "Enter Your Email/Mobile Number",
      "ENTER_YOUR_NEW_MOBILE_NUMBER": "Enter Your New Mobile Number",
      "ERROR": "Error",
      "ERROR_MAIL": "Please Enter Valid Email",
      "ERROR_PASS": "Please Enter Min 6 Digit Password",
      "EXPLORE_BY_CATEGORIES": "Explore by Categories",
      "FAILED": "Failed",
      "FAVORITE": "Favorite",
      "FIRST_NAME": "First Name",
      "FORET_PASS_MESSAGE":
          "Please enter your registered Email to send the reset code",
      "FORGET_PASSWORD": "Forgot Password",
      "FORGET_PASS_MOBILE_MSG":
          "Please enter your registered Mobile Number to send the reset code",
      "FREE": "Free",
      "FULL_NAME": "Full Name",
      "GO_TO_CART": "Go To Cart",
      "HAVE_GOT_AN_ACCOUNT": "Have got an account",
      "HOME": "Home",
      "HOME_PAGE": "Home",
      "HOUSE_FLAT_BLOCK_NUMBER": "House/Flat/Block Number",
      "INVAILD_USER": "Invalid User",
      "ITAMS": "Items",
      "ITEM": "Item",
      "ITEMS": "Items",
      "ITEMS_FOUNDS": "Items Founds",
      "I_ACCEPT": "I accept",
      "LANDMARK": "Landmark",
      "LAST_NAME": "Last Name",
      "LETS_GET_STARTED": "Lets get started",
      "LIMITED_STOCK": "Limited quantity available, you cant add more than",
      "LOCATION": "Location",
      "LOGIN": "Login",
      "LOGOUT": "Logout",
      "LOGOUT_SUCCESSFULL": "Logout Successful",
      "MAIL_US": "Mail Us",
      "MIN_AMOUNT_MEG": "Amount should be greater then or equal min amount",
      "MOBILE_NUMBER": "Mobile Number",
      "MORE_ITEMS": "more items",
      "MY_CART": "My Cart",
      "MY_ORDERS": "My Orders",
      "NEW_MOBILE_NUMBER": "Mobile Number",
      "NO": "No",
      "NO_INTERNET": "No Internet connection",
      "NO_INTERNET_MSG":
          "requires an internet connection. Check your connection then try again.",
      "NO_RESULT_FOUNDS": "No Results Found!",
      "NO_SLOTS": "Sorry No Slots Available Today",
      "OFF": "Off",
      "OF_THIS_ITEM": "of this item",
      "OK": "Ok",
      "ONLINE_MSG": "Now you are online.",
      "OOPS": "Oops",
      "OR": "Or",
      "ORDERED": "Ordered",
      "ORDERS": "Orders",
      "ORDER_ASSIGNED": "Order Assigned",
      "ORDER_CANCELLED": "Order Cancelled",
      "ORDER_CONFIRMED": "Order Confirmed",
      "ORDER_DELIVERED": "Order Delivered",
      "ORDER_DETAILS": "Order Details",
      "ORDER_FROM": "Order From",
      "ORDER_ID": "Order Id",
      "ORDER_NOW": "Order Now",
      "ORDER_PAYMENT": "Order Payment",
      "ORDER_PLACED": "Order Placed",
      "ORDER_STAUS": "Order Status",
      "OTHERS": "Others",
      "OTP_CODE_MSG": "OTP send to your registered mobile number",
      "OTP_MSG": "Please Enter 4 Digits OTP",
      "OTP_MSG_MOBILE": "Please Enter 6 Digits OTP",
      "OUT_FOR_DELIVERY": "Out for Delivery",
      "OUT_OF_STOCK": "Out of Stock",
      "PAID_FORM_WALLET": "Paid From Wallet",
      "PASSWORD": "Password",
      "PASSWORD_RESET": "Password Reset",
      "PASS_NOT_MATCH": "Passwords do not match",
      "PAYABLE_AMOUNT": "Payable Amount",
      "PAYMENT": "Payment",
      "PAYMENT_STATUS": "Payment Status",
      "PAYMENT_TYPE": "Payment Type",
      "PAY_BY_CARD": "Pay By Card",
      "PAY_NOW": "Pay Now",
      "PENDING": "Pending",
      "PLEASE_SUBMIT_YOUR_FEEDBACK": "Please submit your feedback",
      "POSTAL_CODE": "Postal Code",
      "PP_AND_TAND_C": "Privacy Policies and T&C",
      "PRIVACY_POLICY": "Privacy Policy",
      "PROCEED": "Proceed",
      "PRODUCTS": "Products",
      "PROFILE": "Profile",
      "QUANTITY": "Quantity",
      "RATE_DELIVERY": "Rate delivery",
      "RATE_PRODUCT": "Rate Product",
      "RECENT": "Recent",
      "RECENT_TRANSACTIONS": "Recent Transactions",
      "REGISTER": "Register",
      "REMOVE_ITEMS": "Remove Items",
      "REMOVE_PHOTO": "Remove Photo",
      "REMOVE_WALLET": "Remove Wallet",
      "RESENT_OTP": "Resent OTP",
      "RESET": "Reset",
      "RE_ENTER_NEW_PASSWORD": "Re Enter New Password",
      "RE_ORDER": "Re-Order",
      "SAVED_ADDRESS": "Saved Address",
      "SELECT": "Select",
      "SELECT_ADDESS_MSG": "Please select address first",
      "SELECT_LANGUAGE": "Select Language",
      "SELECT_PAYMENT_FIRST": "Select Payment First!",
      "SELECT_TIME_MSG": "Please select time slot first",
      "SELECT_YOUR_COUNTRY": "Select your country",
      "SEND_OTP": "Send OTP",
      "SHARE": "Share",
      "SHARE_MESSAGE": "Visit to this link",
      "SIGNUP": "Sign Up",
      "STORE": "Store",
      "SUBMIT": "Submit",
      "SUBMIT_FEEDBACK": "Submit feedback",
      "SUB_TOTAL": "SubTotal",
      "SUCCESS": "Success",
      "TAKE_PHOTO": "Take Photo",
      "TAX": "Tax",
      "TELL_US_YOUR_EXPERIENCE": "Tell us your experience...",
      "TERMS_CONDITIONS": "Terms And Conditions",
      "THANK_YOU": "Thank You",
      "TIME_ZONE_MESSAGE": "Time is UTC format",
      "TOP_DEALS": "Top Deals",
      "TOTAL": "Total",
      "TOTAL_WALLET_AMOUNT": "Total Wallet Amount",
      "TOTAL_WALLET_BALANCE": "Total Wallet Balance",
      "TRANSACTIONS": "Transactions",
      "TRANSACTION_TYPE": "Transaction Type",
      "TYPE_TO_SEARCH": "Type To Search",
      "UPDATE": "Update",
      "USED_WALLET_AMOUNT": "Used Wallet Amount",
      "USE_WALLET_AMOUNT": "Use Wallet Amount",
      "VERIFY_OTP": "Verify OTP",
      "VERI_LINK": "Send Verification link",
      "VIEW": "View",
      "VIEW_ALL": "View All",
      "WALLET": "Wallet",
      "WALLET_HISTORY": "Wallet History",
      "WELCOME": "Welcome",
      "WELCOME_BACK": "Welcome Back",
      "WHAT_ARE_YOU_BUING_TODAY": "What are you buying today?",
      "WORK": "Work",
      "YES": "Yes",
      "YOUR_LOCATION": "Your Location",
      "YOUR_ORDER_WAS_DELIVERED_BY": "Your order was delivered by"
    }
  };
}
